### ISSUE TITLE
An error is occurring on startup of my velocity proxy instance

### ISSUE THREAD

**Issue by z2vvqx** [akbe2020/ReLimboQ#2]
Here's the full error
```yaml
[19:09:33 WARN] [net.elytrium.limboapi.thirdparty.commons.config.YamlConfig]: Unable to load some of the config options. File was copied to config.yml_backup_2024-10-10_19.09.33
[19:09:34 ERROR]: Exception in task io.github.akbe2020.relimboq.ReLimboQ$$Lambda/0x00007fb088a1d028@6f3470ad by plugin ReLimboQ
java.lang.NullPointerException: Cannot invoke "io.github.akbe2020.relimboq.ReLimboQ$ServerStatus.ordinal()" because "this.serverStatus" is null
        at io.github.akbe2020.relimboq.ReLimboQ.lambda$startQueueTask$4(ReLimboQ.java:200) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[server.jar:3.3.0-SNAPSHOT (git-09f687e5-b413)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]```

**Comment by akbe2020** [comment]
Looks like it is a config provider issue

**Comment by z2vvqx** [comment]
Hey, thanks for replying. I forgot to mention that there's another issue, I set the dimension to OVERWORLD but uses NETHER, I use THE_END/NETHER, it uses OVERWORLD

**Comment by akbe2020** [comment]
Currently, ReLimboQ is in the alpha stage, so there may be many issues. Unfortunately, I don't have enough time to maintain the project at the moment. However, you can fix the issue yourself and then submit the changes as a pull request.
